### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by triblondon** [Octane/Promise#10]
Testing in the polyfill service was showing that this polyfill worked in all our test browsers, but actually that turns out to have been due to a bug in the tests.  Could you post browser support numbers on the README of the project?

Here are our results with your polyfill:

IE: 11, 10, 9 pass;  8, 7, 6 fail
FF: 29, 33, 34 native; 20 pass; 3.6 fail
Chrome: 24 native; 26 pass
Safari: 5, 6, 7 pass

**Comment by Octane** [comment]
I tested the polyfill in IE8+. I didn't even try to test in IE6,7.
On my [test page](https://octane.github.io/promise/tests/browser.html) the polyfill passes all tests in IE8.
Most likely your version doesn't work in IE8, because the implementation of `_enqueueMicrotask` doesn't use `onreadystatechange` event in IE8.

The examples of readystatechange-based implementations for IE8:
- [YuzuJS/setImmediate](https://github.com/YuzuJS/setImmediate/blob/master/setImmediate.js#L128)
- [Octane/setImmediate](https://github.com/Octane/setImmediate/blob/master/setimmediate-ie8.js#L44)
- [Financial-Times/setImmediate](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/setImmediate/polyfill-onreadystatechange.js#L12)

Ok, I'll add a list of supported browsers to the README.

**Comment by triblondon** [comment]
Ah, OK, I'll take another look at enqueueMicrotask

**Comment by triblondon** [comment]
Thanks, your setImmediate polyfill works a treat.  It's worth advising developers who intend to use this in IE8 that `catch` cannot be called using the literal function name and needs to be `['catch']`.  I've made a note of that in our docs.

**Comment by triblondon** [comment]
Clearing up some of my old issues, this one seems to be closable.
